### ISSUE TITLE
Jetson Nano, Jetpack 4.6

### ISSUE THREAD

**Issue by programmeddeath1** [Qengineering/PyTorch-Jetson-Nano#5]
Hi Team
Thank you for your efforts to build and make the torch files available!

I want to know two things
1) Are the torch files built using CUDA? I had installed the default torch provided by nvidia it doesnt use CUDA.
2) I am getting an error as below when i install any of the 4 torch files (1.7 to 1.10).
```
"import torch; print(torch.__version__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "venv/lib/python3.6/site-packages/torch/__init__.py", line 196, in <module>
    _load_global_deps()
  File "venv/lib/python3.6/site-packages/torch/__init__.py", line 149, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcurand.so.10: cannot open shared object file: No such file or directory
```

Do you know what could be causing the issue?
Thank your for your help in advance!

**Comment by Qengineering** [comment]
First question: Yes, we compile the wheel with CUDA and cuDNN acceleration.

The second issue can be a nightmare.
We've downloaded our PyTorch 1.10 wheel and installed it on a clean machine to see if we can reproduce the error.
However, it doesn't give any problem.

![Screenshot from 2022-12-30 13-26-34](https://user-images.githubusercontent.com/44409029/210070486-745fb4f7-814c-4c4f-9c2b-e64987ded1cf.png)
![Screenshot from 2022-12-30 13-26-27](https://user-images.githubusercontent.com/44409029/210070495-e982da90-973e-40ce-8f8c-d5fee1a21562.png)

On the other hand, when googling your error, we get some hits. Please see for instance [this topic](https://forums.developer.nvidia.com/t/installing-pytorch-oserror-libcurand-so-10-cannot-open-shared-object-file-no-such-file-or-directory/165044/9).
